memo/urls.py
from .import views
from django.urls import path

app_name = 'memo'
urlpatterns=[
    path('',views.IndexView.as_view(),name='index'),
    path('inquiry/',views.InquiryView.as_view(),name='inquiry'),
    path('memo-list/',views.MemoListView.as_view(),name='memo_list'),
    path('memo-detail/<int:pk>/', views.MemoDetailView.as_view(), name='memo_detail'),
    path('memo-create/', views.MemoCreateView.as_view(), name='memo_create'),
    path('memo-update/<int:pk>/', views.MemoUpdateView.as_view(), name='memo_update'),
    path('memo-delete/<int:pk>/', views.MemoDeleteView.as_view(), name='memo_delete'),
]

public_memo/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include

from . import settings_common

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('memo.urls')),
    path('accounts/',include('allauth.urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):

    class Meta:
        verbose_name_plural = 'CustomUser'
# Create your models here.

memo/models.py
from accounts.models import CustomUser
from django.db import models

# Create your models here.


class Memo (models.Model):
    
    user = models.ForeignKey(CustomUser,verbose_name='ユーザー',on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル',max_length=40)
    content = models.TextField(verbose_name='本文',blank=True,null=True)
    created_at = models.DateTimeField(verbose_name='作成日時',auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now_add=True)

    class Meta:
        verbose_name_plural = 'memo'

    def __str__(self):
        return self.title

memo/forms.py
from django import forms
from django.core.mail import EmailMessage
from .models import Memo

class InquiryForm(forms.Form):
    name=forms.CharField(label='お名前',max_length=30)
    email=forms.EmailField(label='メールアドレス')
    title=forms.CharField(label='タイトル',max_length=30)
    message = forms.CharField(label='メッセージ',widget=forms.Textarea)

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        self.fields['name'].widget.attrs['class']='form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] ='お名前を入れてください'
        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください'
        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください'
        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名: {0}\nメールアドレス:　{1}/nメッセージ:\n{2}'.format(name,email,message)
        from_email = 'admin@example.com'
        to_list=[
            'test@example.com'
        ]
        cc_list=[
            email
        ]
        message = EmailMessage(subject=subject,body=message,from_email=from_email,to=to_list,cc=cc_list)
        message.send()

class MemoCreateForm(forms.ModelForm):
    class Meta:
        model = Memo
        fields = ('title','content')
        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            for field in self.fields.values():
                field.widget.attrs['class'] = 'form-control'

accounts/views.py
from django.shortcuts import render

# Create your views here.

memo/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
import logging
from .models import Memo
from .forms import InquiryForm , MemoCreateForm

logger= logging.getLogger(__name__)

class IndexView(generic.TemplateView):
    template_name = "index.html"

class InquiryView(generic.TemplateView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('memo:inquiry')

    def form_valid(self,form):
        form.send_email()
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)



class MemoListView(LoginRequiredMixin,generic.ListView):
    model = Memo
    template_name =  "memo_list.html"
    pageinate_by = 2

    def get_queryset(self):
        memos = Memo.objects.filter(user=self.request.user).order_by('created_at')
        return memos

class MemoDetailView(LoginRequiredMixin,generic.DetailView):
    model = Memo
    template_name = 'memo_detail.html'
    #pk_url_kwarg = 'id'

class MemoCreateView(LoginRequiredMixin,generic.CreateView):
    model = Memo
    template_name = 'memo_create.html'
    form_class = MemoCreateForm
    success_url = reverse_lazy('memo:memo_list')

    def form_valid(self, form):
        memo = form.save(commit=False)
        memo.user = self.request.user
        memo.save()
        messages.success(self.request,"メモを作成しました。")
        return super().form_valid(form)
    def form_invalid(self, form):
        messages.error(self.request,"メモの作成に失敗しました")

class MemoUpdateView(LoginRequiredMixin,generic.UpdateView):
    model = Memo
    template_name = 'memo_update.html'
    form_class = MemoCreateForm

    def get_success_url(self):
        return reverse_lazy('memo:memo_detail',kwargs={'pk':self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request,'メモを更新しました')
        return super().form_valid(form)

    def form_vallid(self, form):
        messages.success(self.request,'メモを更新を失敗しました')
        return super().form_valid(form)

class MemoDeleteView(LoginRequiredMixin, generic.DeleteView):
    model =  Memo
    template_name = 'memo_delete.html'
    success_url = reverse_lazy('memo:memo_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request,"メモを削除しました。")
        return super().delete(request,*args,**kwargs)

memo/templates/base.html
{% load static %}

<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrin-to-fit=no">
    <meta name="discriotion" content="">
    <meta name="author" content="">
    <title>{%block title%}{% endblock %}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900,">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,700,700i,900,900i,">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/one-page-wonder.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container">
                <a href="{% url 'memo:index' %}" class="navbar-brand">private memo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav mr-auto">
<!--                        <li class="nav-item {% block active_inquiry %}{% endblock %}">-->
<!--                            <a href="{% url 'memo:inquiry'%}" class="nav-link">inquiry</a>-->
<!--                        </li>-->
                    {% if user.is_authenticated %}
                    <li class="nav-item {% block active_memo_list %}{% endblock %}">
                        <a href="{% url 'memo:memo_list'%}" class="nav-link">MEMO LIST</a>
                    </li>
                    {% endif %}
                    </ul>
                    <ul class="navbar-nav ml-auto">

                        {% if user.is_authenticated %}

                        <li class="nav-item">
                            <a href="{% url 'account_logout' %}" class="nav-link">Log Out</a>
                        </li>

                        {% else %}

                        <li class="nav-item {% block active_signup %}{% endblock %}">
                            <a href="{% url 'account_signup' %}" class="nav-link">Sign Up</a>
                        </li>
                        <li class="nav-item {% block active_login %}{% endblock %}">
                            <a href="{% url 'account_login' %}" class="nav-link">Log In</a>
                        </li>

                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block header%}{% endblock %}

        {% if messages %}
            <div class="container">
                <div class="row">
                    <div class="my-div-style w-100">
                        <ul class="message"style="list-style:none;">
                            {% for message in messages%}
                            <li {%if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        {% endif %}

        {% block contents%}{% endblock %}
        <footer class="py-5 bg-black">
            <div class="container">
                <p class="m-0 text-center text white small">Copyright &copy; Private Memo 2020</p>
            </div>
        </footer>

        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    </div>
</body>
</html>

memo/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Web上にあなた専用のメモが残せるサービス|Private Diary{%endblock %}

{% block header%}
  <header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0">Private Memo</h1>
        <h2 class="masthead-subheading mb-0">あなた専用のメモ保存サービス</h2>
        <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5">Log In</a>
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>
{% endblock %}

{% block contents %}
  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'img/01.jpg'%}" alt="">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-5">
            <h2 class="display-4">Web Memo</h2>
            <p>web上で作成・編集・削除ができる日記</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'img/02.jpg' %}" alt="">
          </div>
        </div>
        <div class="col-lg-6">
          <div class="p-5">
            <h2 class="display-4">Save Your Memo</h2>
            <p>あなたのメモをWebに保存</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'img/03.jpg'%}" alt="">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-5">
            <h2 class="display-4">Membership systems</h2>
            <p>会員制のWebメモサービス</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  {% endblock %}

memo/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ|Private Diary{% endblock %}
{% block active_inquiry %}active{% endblock %}
{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}

                {{ form.non_errors }}

                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                            <strong>{{fields.label_tag}}</strong>
                        </label>
                        <div class="col-sm-8">
                            {{field}}
                            {{field.errors}}
                        </div>
                    </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

memo/templates/memo_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}MemoList|public Memo{% endblock %}

{% block active_memo_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

memo/templates/memo_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MemoUpdate|public Memo{% endblock %}
{% block active_memo_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>ほんとに削除しますか？</p>
                <button class="btn btn-primary mt-5" type="submit">削除</button>
                <a href="{% url 'memo:memo_detail' object.pk %}" class="btn btn-secondary ml-2">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

memo/templates/memo_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}日記詳細|Private Diary{% endblock %}
{% block active_memo_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style w-100">
        <div class="row">
            <div class="col-3">
                <strong>タイトル</strong>
            </div>
            <div class="col-9">
                {{object.title}}
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-3">
                <strong>本文</strong>
            </div>
            <div class="col-9">
                {{ object.content|linebreaksbr }}
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-3">
                <strong>制作日時</strong>
            </div>
            <div class="col-9">
                {{object.created_at}}
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-3">
                <strong>更新日時</strong>
            </div>
            <div class="col-9">
                {{object.updated_at}}
            </div>
        </div>

        <a href="{% url 'memo:memo_update' memo.pk %}" class="btn btn-success mt-5 mb-3">編集</a>
        <a href="{% url 'memo:memo_delete' memo.pk %}" class="btn btn-denger mt-5 mb-3">削除</a>
    </div>
</div>
{% endblock %}

memo/templates/memo_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}MemoList|public Memo{% endblock %}

{% block active_memo_list %}active{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min' %}">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg col-md-10 mx-auto">
                <div class="clearfix">
                    <a href="{% url 'memo:memo_create' %}" class="btn btn-primary float-right">新規作成</a>
                </div>
                {% for memo in memo_list %}
                   <div class="post-preview">
                      <a href="{% url 'memo:memo_detail' memo.pk %}">
                          <h2 class="post-title">
                              {{memo.title}}
                          </h2>
                          <h3 class="post-title">
                              {{ memo.content|truncatechars:20 }}
                          </h3>
                      </a>
                      <p class="post-meta">{{memo.created_at}}</p>
                   </div>
                    <hr>
                    {% empty %}
                        <p>メモがありません。</p>
                    {% endfor %}

                {% if is_paginated %}
                    <ul class="paginated">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a href="?page={{page_obj.previous_page_number}}" class="page-link">
                                    <span area-hiddon="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}

                        {% for page_num in page_obj.paginator.page_range %}
                            {% if page_obj.number == page_num %}
                                <li class="page-item active">
                                    <a href="#" class="page-link"></a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a href="?page={{ page_num }}" class="page-link">
                                        <span area-hiddon="true">{{page_num}}</span>
                                    </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.next %}
                            <li class="page-item">
                                <a href="{{page_obj.next_page_number}}" class="page-link">
                                    <span area-hiddon="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

memo/templates/memo_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MemoUpdate|public Memo{% endblock %}
{% block active_memo_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">Update</button>
                <a href="{% url 'memo:memo_detail' memo.pk %}" class="btn btn-secondary ml-2">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}